#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const skillPath = join(pkgRoot, "SKILL.md");
const outPath = join(pkgRoot, "src", "skill-content.gen.ts");

const raw = readFileSync(skillPath, "utf8");
const escaped = raw
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/gen-skill.mjs — do not edit by hand.
// Source: packages/rote/SKILL.md
export const SKILL_MD = \`${escaped}\`;
`,
);

console.error(`gen-skill: wrote ${outPath} (${raw.length} bytes)`);
